### ISSUE TITLE
Unable to use numeric-only strings for legend

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/PDL-Graphics-Gnuplot#100]
Using PDL::Graphics::Gnuplot version 2.024, PDL 2.080, Perl 5.34.1:

```perl
use PDL::Graphics::Gnuplot
$w=gpwin("wxt",size=>6);
$x=xvals(10); $y = $x**2;
$w->plot({with=>'lines',legend=>'parabola'},$x,$y);
$w->plot({with=>'lines',legend=>'123parabola'},$x,$y);
$w->plot({with=>'lines',legend=>'456'},$x,$y);
```
> Can't use string ("456") as an ARRAY ref while "strict refs" in use at /Users/derek/Build/PDL-Graphics-Gnuplot/blib/lib/PDL/Graphics/Gnuplot.pm line 3867.

**Comment by sisyphus** [comment]
It's the evaluation of <code>@{$chunk{options}->{legend}}</code> in Gnuplot.pm that's causing the error.
I didn't go digging, but I can only think that, somehow, with 'parabola' and '123parabola' $chunk{options}{legend} is set to something like<code>['parabola']</code> and (respectively) <code>['123parabola']</code>, but with '456' it's set to<code>'456'</code>.

Maybe something along the lines of what is accomplished by this silly little script:
```
use strict;
use warnings;
use Scalar::Util 'looks_like_number';

for ('parabola', '123parabola', '456') {
  my $arg;
  if(!looks_like_number($_)) {$arg = [$_]}
  else {$arg = $_}
  my %h = ('legend', $arg);
  my %chunk = ('options', \%h);
  print "ok: $_\n" if @{$chunk{options}->{legend}};
}

__END__
Outputs:
ok: parabola
ok: 123parabola
Can't use string ("456") as an ARRAY ref while "strict refs" in use at try.pl line 11.
```
Cheers,
Rob
