### ISSUE TITLE
wxt terminal possibly misconfigured

### ISSUE THREAD

**Issue by bruceravel** [PDLPorters/PDL-Graphics-Gnuplot#59]
Why is the wxt terminal marked as being a non-mousing terminal?  See

https://github.com/drzowie/PDL-Graphics-Gnuplot/blob/master/lib/PDL/Graphics/Gnuplot.pm#L6895

The mouse interaction certainly works on wxt, so I think it should be ``mouse=>1``.

**Comment by drzowie** [comment]
For some reason it hasn't been working in read_polygon, and I haven't had the tuits to look into it and get it working right.

**Comment by mohawk2** [comment]
In fact @drzowie did enable `mouse` about a month later, in 1aa474230dc417fbdf087bda0be75563adc5f425. Closing.
