### ISSUE TITLE
Current version requires PDL::Transform::Color, which is not in CPAN

### ISSUE THREAD

**Issue by drzowie** [PDLPorters/PDL-Graphics-Gnuplot#70]
As of 20-July-2020, PDL::Graphics::Gnuplot won't install via CPAN because a prerequisite (PDL::Transform::Color) is not in CPAN.  

The solution is to upload PDL::Transform::Color to PAUSE.

**Comment by d-lamb** [comment]
Closing, this now [exists on CPAN](https://metacpan.org/pod/PDL::Transform::Color).
